version: 0.2
env:
  variables:
    AUTOTEST_CONFIG: "codebuild.conf"
    EQ_EXIFTOOL_PATH: "/usr/bin/exiftool"
phases:
  install:
    commands:
      - . setupBuildCommands
      - npm install -g yarn
      - mkdir -p ~/.sbt/1.0/
      - cp codebuild/global.sbt ~/.sbt/1.0/
      - service postgresql start
      - curl -OL https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
      - unzip -o -d ${HOME} chromedriver_linux64.zip
      - (cd $HOME && curl -OL $INSTALLER_DOWNLOAD)
  build:
    commands:
      - sbt -no-colors installEquella startEquella
      - sbt -no-colors configureInstall setupForTests ${OTHER_TESTS}
      - sbt -no-colors Tests/test
  post_build:
    commands:
      - sbt -no-colors coverageReport ; publishTestResults
artifacts:
  files:
    - 'OldTests/target/testng/**/*'
    - 'Tests/target/test-reports/**/*'
    - 'target/coverage-report/**/*'
    - 'equella-install/logs/**/*'
  name: $(testFolder)

cache:
  paths:
    - '/root/.ivy2/**/*'
    - '/root/.npm/**/*'
    - '/root/.sbt/**/*'
